version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm ci
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync dist/ "s3://the-energy-hour" --delete
      - aws cloudfront create-invalidation --distribution-id "E7A8JILDM72BF" --paths '/*'

artifacts:
  files:
    - '**/*'
  base-directory: dist

cache:
  paths:
    - node_modules/**/*